const actionTypes = Object.freeze({

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIDED: 'FETCH_GENDER_FAIDED',

    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIDED: 'FETCH_POSITION_FAIDED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIDED: 'FETCH_ROLE_FAIDED',

    // FETCH_PRICE_START: 'FETCH_PRICE_START',
    // FETCH_PRICE_SUCCESS: 'FETCH_PRICE_SUCCESS',
    // FETCH_PRICE_FAIDED: 'FETCH_PRICE_FAIDED',

    // FETCH_PAYMENT_START: 'FETCH_PAYMENT_START',
    // FETCH_PAYMENT_SUCCESS: 'FETCH_PAYMENT_SUCCESS',
    // FETCH_PAYMENT_FAIDED: 'FETCH_PAYMENT_FAIDED',

    // FETCH_PROVINCE_START: 'FETCH_PROVINCE_START',
    // FETCH_PROVINCE_SUCCESS: 'FETCH_PROVINCE_SUCCESS',
    // FETCH_PROVINCE_FAIDED: 'FETCH_PROVINCE_FAIDED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FALIDED: 'CREATE_USER_FALIDED',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIDED: 'FETCH_ALL_USER_FAIDED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIDED: 'DELETE_USER_FAIDED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAIDED: 'EDIT_USER_FAIDED',

    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAIDED: 'FETCH_TOP_DOCTOR_FAIDED',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAIDED: 'FETCH_ALL_DOCTOR_FAIDED',

    SAVE_INFOR_DOCTOR_SUCCESS: 'SAVE_INFOR_DOCTOR_SUCCESS',
    SAVE_INFOR_DOCTOR_FAIDED: 'SAVE_INFOR_DOCTOR_FAIDED',

    FETCH_SCHEDULE_HOURS_SUCCESS: 'FETCH_SCHEDULE_HOURS_SUCCESS',
    FETCH_SCHEDULE_HOURS_FAIDED: 'FETCH_SCHEDULE_HOURS_FAIDED',

    FETCH_REQUIRED_DOCTOR_INFOR_START: 'FETCH_REQUIRED_DOCTOR_INFOR_START',
    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFOR_FAIDED: 'FETCH_REQUIRED_DOCTOR_INFOR_FAIDED',


    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: ' USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


})

export default actionTypes;